on:
  workflow_dispatch: {}
  push:
    branches:
    - main
    paths:
    - .github/workflows/semgrep.yml
name: Semgrep Findings
jobs:
  semgrep-free:
    name: Semgrep-free
    runs-on: ubuntu-20.04
    container:
      image: semgrep/semgrep
    steps:
    - uses: actions/checkout@v4
    - name: Semgrep scan
      run: |
        # Run Semgrep scan and store the output in JSON
        semgrep scan --json --json-output /tmp/semgrep.json
      env:
          SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_APP_TOKEN }}

    - name: View the output
      run: |
        ls -la /tmp
        cat /tmp/semgrep.json

    - name: Upload report to AccuKnox
      run: |
        curl --location --request POST \
        "https://cspm.demo.accuknox.com/api/v1/artifact/?tenant_id=${{ secrets.ACCUKNOX_TENANT_ID }}&data_type=SG&save_to_s3=true&label_id=${{ secrets.ACCUKNOX_LABEL }}" \
              --header "Tenant-Id: {{ secrets.ACCUKNOX_TENANT_ID }}" \
              --header "Authorization: Bearer {{ secrets.ACCUKNOX_TOKEN }}" \
              --form "file=@/tmp/semgrep.json"

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: semgrep-report
        path: /tmp/semgrep.json